[Frontend] remove angular server, replaced with static files
ISG-ICS/Wildfires pull request #8
Opened 2019-10-11 22:59 UTC by AC-Unicorn

### Logits of this PR
1. Enhance the stability of the app by removing angular server, instead of serving static files using backend server
2. Change the appearance of user-interface to make it cleaner 

### Changes of this PR
1.disable polygon fill color 
2.remove sidebar (comment out)
3.reduce default zoom level to enlarge viewport 
4. config router for static frontend
5. Change backend port 
6. Build static frontend with the new port, but the environment file stays unchanged.

### Future improvement
1. Current frontend doesn't support build(ng build --prod) with production mode (not capable with building in AOT(ahead of time) mode), we need to modify codebase to fulfill this requirement, the changes can be many, so I leave them in next PR.

2019-10-12 15:28 UTC, Yicong-Huang requested changes
Some minor changes required.

I really do not want to expose port 2333 in the git history of master branch, can you reset the port to be default?

Also to ease the deployment, maybe we do not need to commit all the static files (since they will be build each time differently). Can you instead leave a bash file in the repo root, so it can do the following:
1. take in the host and port as command line parameters;
2. generate static frontend files with the given host and port;
3. mv the generated static frontend files to backend static/ directory (or just generate the static files to static/ directory directly);
4. start the backend server. 

Thank you

2019-10-12 15:28 UTC, Yicong-Huang commented on backend/web/__init__.py
> +    server_app.run(port=2333, debug=True)
can this be left not changed?

2019-10-12 15:28 UTC, Yicong-Huang commented on backend/web/static/index.html
> +  <title>WildfiresFrontend</title>
change the title to be `Wildfires Map`

2019-10-12 15:29 UTC, Yicong-Huang commented
fix  #3

2019-10-15 02:42 UTC, Yicong-Huang commented
is this PR ready for review?

2019-10-15 04:52 UTC, AC-Unicorn commented
Currently, we still can't build in production mode ( Or aot mode) since the leaflet error still exists.
The reason is unclear. So I changed build command in "Package.json" back to default build mode. 
I think we can merge the PR right now, and I'll do more research about the error, since the reason might be non-trivial.

2019-10-15 05:22 UTC, Yicong-Huang commented
I've just tested on server with host changed to `0.0.0.0`. it still gives me the error 
```
ReferenceError: Can't find variable: L
```

2019-10-15 05:39 UTC, AC-Unicorn commented
> I've just tested on server with host changed to `0.0.0.0`. it still gives me the error
> 
> ```
> ReferenceError: Can't find variable: L
> ```

Did you use "Empty Cache and Hard Reload"? assuming you are using chrome.

2019-10-15 05:44 UTC, Yicong-Huang commented
OK that works. but it still cannot talk to backend. please change the production environment to be `host='0.0.0.0'` in frontend

2019-10-15 05:57 UTC, Yicong-Huang commented
interesting, it still shows that 
```
[Error] Failed to load resource: Could not connect to the server. (recent-temp, line 0)
[Error] Failed to load resource: Could not connect to the server. (fire-tweet, line 0)
[Error] Failed to load resource: Could not connect to the server. (fire-polygon, line 0)
[Error] Failed to load resource: Could not connect to the server. (boundaries, line 0)
[Error] Failed to load resource: Could not connect to the server. (wind, line 0)
[Error] Failed to load resource: Could not connect to the server. (recent-tweet, line 0)
[Error] Failed to load resource: Could not connect to the server. (tweet-count, line 0)```

2019-10-15 06:15 UTC, AC-Unicorn commented
> interesting, it still shows that
> 
> `[Error] Failed to load resource: Could not connect to the server. (tweet-count, line 0)http://0.0.0.0:2333/data/recent-temp`

Is the backend server running on 2333?

2019-10-15 16:15 UTC, Yicong-Huang commented
yes, the backend is severing on 2333. 

and I can get response with 
`http://wildfires.ics.uci.edu:2333/data/recent-temp`

2019-10-15 17:03 UTC, Yicong-Huang commented
I've manually changed the `environment.ts`
for the host to be `wildfires.ics.uci.edu` and it is working now.

However we'd better fix the prod mode soon.

2019-10-18 07:31 UTC, AC-Unicorn commented
By adding a statement in polyfill.js, now the frontend can be compiled in production mode.
Angular will build the project into two bundles, one uses ES2015 syntax another one uses ES5 syntax which is older. To be compatible with all browsers, Polyfills in angular are few lines of code which make your application compatible for different browsers.

2019-10-22 17:12 UTC, Yicong-Huang commented
I will postpone merging this PR as it is a relatively hacky way. the online demo is using this branch now.

2019-11-05 22:48 UTC, merged

2019-11-05 22:49 UTC, Yicong-Huang commented
fixed #3